apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <mfppvc>
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
