##############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}" 
  annotations:
    ingress.kubernetes.io/client-max-body-size: "200m"
    ingress.kubernetes.io/proxy-read-timeout: "300s"
    ingress.kubernetes.io/proxy-connect-timeout: "300s"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /mfpconsole
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 9080
      - path: /mfp
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 9080
      - path: /imfpush
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 9080
      - path: /mfpadmin
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 9080
      - path: /mfpadminconfig
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 9080
      - path: /doc
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 9080
{{- if .Values.ingress.sslSecretName }}
  tls:
  - hosts:
    secretName: {{ .Values.ingress.sslSecretName }}
{{- end }}
{{- end }}
