###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################

###############################################################################
# Default values for ibm-mobilefirst-foundation-appcenter
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

###############################################################################
## Architecture - e.g. amd64, s390x, ppc64le. If left empty, arch type will try
## to be determined.
## You can use kubectl version command to determine the architecture on the
## desired worker node.
###############################################################################
arch: "amd64"

#####################################################
# APPLICATION CENTER SPECIFIC VARIABLES
image:
  name: mfpf-appcenter
  tag: latest
  pullPolicy: IfNotPresent
mobileFirstAppCenterConsole:
  user: "admin"
  password: "admin"
existingDB2Details:
  appCenterDB2Host: ""
  appCenterDB2Port: ""
  appCenterDB2Username: ""
  appCenterDB2Password: ""
  appCenterDB2Database: ""
  appCenterDB2Schema: ""
  appCenterDB2ConnectionIsSSL: false
#####################################################
## Keystores
keystores:
  keystoresSecretName: ""

###############################################################################
## Ingress
###############################################################################
ingress:
  enabled: false
  sslSecretName:

#####################################################
# VARIABLES COMMON TO THE WHOLE DEPLOYMENT
resources:
  requests:
    cpu: 1000m
    memory: 2048Mi
  limits:
    cpu: 2000m
    memory: 4096Mi

#####################################################
