###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################

###############################################################################
# Default values for ibm-mobilefirst-foundation-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
###############################################################################

###############################################################################
## Architecture - e.g. amd64, s390x, ppc64le. If left empty, arch type will try
## to be determined. 
## You can use kubectl version command to determine the architecture on the 
## desired worker node. 
###############################################################################
arch: "amd64"

###############################################################################
## Common image variables
###############################################################################
image:
  name: registry.ng.bluemix.net/prashanthspace/mfpf
  tag: 9
  pullPolicy: IfNotPresent

###############################################################################
## Scaling
###############################################################################
scaling:
  replicaCount: 1

###############################################################################
## MobileFirst Operations Console Credentials
###############################################################################
mobileFirstOperationsConsole:
  user: "admin"
  password: "admin"

###############################################################################
## Existing DB2 database details for the MobileFirst database
###############################################################################
existingDB2Details:
  db2Host: "dashdb-txn-small-yp-dal09-01.services.dal.bluemix.net"
  db2Port: "50000"
  db2Username: "bluadmin"
  db2Password: "NTZjYWJkYjdjNmQ3"
  db2Database: "BLUDB"
  db2Schema: "HELMTEST"
  db2ConnectionIsSSL: false

###############################################################################
## Existing MobileFirst Operational Analytics 
###############################################################################
existingMobileFirstAnalytics:
  analyticsEndpoint: ""
  analyticsAdminUser: ""
  analyticsAdminPassword: ""

###############################################################################
## MobileFirst Server specific details
###############################################################################
keystores:
  keystoresSecretName: ""
  
jndiConfigurations:
  mfpfProperties: ""

###############################################################################
## Ingress
###############################################################################
ingress:
  enabled: false
  sslSecretName:

###############################################################################
## Resource constraints
###############################################################################
resources:
  requests:
    cpu: 750m
    memory: 1024Mi
  limits:
    cpu: 750m
    memory: 1024Mi
